### ISSUE TITLE
最近会增加Tabbar、NavBar、Pagination、Grid、IndexBar等等组件么？

### ISSUE THREAD

**Issue by ChuangShiOS** [webyom/pant-react#1]
### What problem does this feature solve
你好 很开心找到一个很好的React UI，我想问一下最近有打算增加新的组件？，最后祝开源越来越好，谢谢啦。

**Comment by webyom** [comment]
@ChuangShiOS 你好，谢谢你的肯定。最近增加了DataList和Cascader，你提到的几个组件都比较简单，后面会优先实现，但不能保证时间。也欢迎一起共建。
